name: Commit Issue Workflow
on:
  schedule:
    - cron: '0 * * * *' #runs every hour
jobs:
  commit_issue_job:
    runs-on: ubuntu-latest
    name: A job to create an issue if a commit was made
    steps:
      - uses: actions/checkout@v1
      - name: Commit issue action step
        id: issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/actions/commit-issue-action
        with:
          sourceRepo: 'tree-sitter/tree-sitter-python'
          targetRepo: 'legesher/tree-sitter-legesher-python'
          issueLabels: 'Type: Maintenance, Status: Available, Status: Review Needed'
      - name: Get the issue url if commits found
        if: success() && steps.issue.outputs.issue_url != ''
        run: |
          echo "The created issue can be found here: ${{ steps.issue.outputs.issue_url }}"
